// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
)

type CreateProjectInput struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Mutation struct {
}

type Project struct {
	ID          uint          `json:"id"`
	Name        string        `json:"name"`
	Description string        `json:"description"`
	UUID        string        `json:"uuid"`
	Status      ProjectStatus `json:"status"`
}

type ProjectResponseGet struct {
	Total    uint       `json:"total"`
	Projects []*Project `json:"projects,omitempty"`
}

type Query struct {
}

type Role struct {
	ID          uint   `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Active      bool   `json:"active"`
}

type UpdateProjectInput struct {
	ID          uint           `json:"id"`
	Name        *string        `json:"name,omitempty"`
	Description *string        `json:"description,omitempty"`
	Status      *ProjectStatus `json:"status,omitempty"`
}

type User struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserGet struct {
	ID       uint   `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	UUID     string `json:"uuid"`
	Disabled bool   `json:"disabled"`
}

type UserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserResponseGet struct {
	Total uint       `json:"total"`
	Users []*UserGet `json:"users,omitempty"`
}

type UserUdateInput struct {
	Name     *string `json:"name,omitempty"`
	Email    *string `json:"email,omitempty"`
	Disabled *bool   `json:"disabled,omitempty"`
}

type ProjectStatus string

const (
	ProjectStatusPlanning   ProjectStatus = "Planning"
	ProjectStatusInProgress ProjectStatus = "InProgress"
	ProjectStatusCompleted  ProjectStatus = "Completed"
)

var AllProjectStatus = []ProjectStatus{
	ProjectStatusPlanning,
	ProjectStatusInProgress,
	ProjectStatusCompleted,
}

func (e ProjectStatus) IsValid() bool {
	switch e {
	case ProjectStatusPlanning, ProjectStatusInProgress, ProjectStatusCompleted:
		return true
	}
	return false
}

func (e ProjectStatus) String() string {
	return string(e)
}

func (e *ProjectStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectStatus", str)
	}
	return nil
}

func (e ProjectStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
