package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.60

import (
	"context"
	"fmt"
	"time"

	"github.com/mitchellh/mapstructure"
	"gorm.io/gorm/clause"
	"open-btm.com/graph/model"
	"open-btm.com/models"
)

// Createsprint is the resolver for the createsprint field.
func (r *mutationResolver) Createsprint(ctx context.Context, input model.CreateSprintInput) (*model.Sprint, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//created sprint initalization
	create_sprint := new(model.Sprint)

	//  initiate -> sprint
	sprint := new(models.Sprint)
	sprint.Name = input.Name
	sprint.Description = input.Description
	sprint.Status = input.Status.String()
	start_time, _ := time.Parse("02-01-2006", input.StartDate)
	sprint.StartDate = start_time.Format("2006-01-02 15:04:05")
	sprint.Duration = input.Duration

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add sprint using transaction if values are valid
	if err := tx.Create(&sprint).Error; err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(sprint, &create_sprint); err != nil {
		return nil, err
	}
	return create_sprint, nil
}

// Updatesprint is the resolver for the updatesprint field.
func (r *mutationResolver) Updatesprint(ctx context.Context, input model.UpdateSprintInput) (*model.Sprint, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// updated up for return if transaction success
	update_sprint := new(model.Sprint)

	// startng update transaction
	var sprint models.Sprint
	// Check if the record exists
	if err := db.WithContext(tracer.Tracer).First(&sprint, input.ID).Error; err != nil {
		return nil, err
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add sprint using transaction if values are valid
	if err := tx.Model(&sprint).UpdateColumns(*&input).Error; err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(sprint, &update_sprint); err != nil {
		return nil, err
	}
	return update_sprint, nil
}

// Deletesprint is the resolver for the deletesprint field.
func (r *mutationResolver) Deletesprint(ctx context.Context, id uint) (bool, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// startng update transaction
	var sprint models.Sprint

	// Check if the record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", uint(id)).First(&sprint).Error; err != nil {
		return false, err
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete sprint using transaction if values are valid
	if err := db.Delete(&sprint).Error; err != nil {
		tx.Rollback()
		return false, err
	}
	// close transaction
	tx.Commit()

	return true, nil
}

// Createrequirementsprint is the resolver for the createrequirementsprint field.
func (r *mutationResolver) Createrequirementsprint(ctx context.Context, requirementID uint, sprintID uint) (*model.Requirement, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//sprint_requirement for return if transaction success
	sprint_requirement := new(model.Requirement)

	// updateing requirement transaction
	var sprint models.Sprint

	// Check if the sprint record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", sprintID).First(&sprint, sprintID).Error; err != nil {
		fmt.Println("Glitched at sprint")
		fmt.Println(sprintID)
		return nil, err
	}
	// Check if the requirement record exists
	var requirement models.Requirement
	if res := db.WithContext(tracer.Tracer).Model(&models.Requirement{}).Where("id = ?", requirementID).First(&requirement); res.Error != nil {
		fmt.Println("Glitched at requirment")
		fmt.Println(requirementID)
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add requirement to sprint data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&sprint).Association("Requirements").Append(&requirement); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(requirement, &sprint_requirement); err != nil {
		return nil, err
	}
	return sprint_requirement, nil
}

// Deleterequirementsprint is the resolver for the deleterequirementsprint field.
func (r *mutationResolver) Deleterequirementsprint(ctx context.Context, requirementID uint, sprintID uint) (*model.Requirement, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//sprint_requirement for return if transaction success
	sprint_requirement := new(model.Requirement)

	// updateing requirement transaction
	var sprint models.Sprint

	// Check if the sprint record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", sprintID).First(&sprint).Error; err != nil {
		return nil, err
	}

	// Check if the requirement record exists
	var requirement models.Requirement
	if res := db.WithContext(tracer.Tracer).Model(&models.Requirement{}).Where("id = ?", requirementID).First(&requirement); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete  data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&sprint).Association("Requirements").Delete(&requirement); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(requirement, &sprint_requirement); err != nil {
		return nil, err
	}
	return sprint_requirement, nil
}

// Createdocumentsprint is the resolver for the createdocumentsprint field.
func (r *mutationResolver) Createdocumentsprint(ctx context.Context, documentID uint, sprintID uint) (*model.Document, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//sprint_document for return if transaction success
	sprint_document := new(model.Document)

	// updateing document transaction
	var sprint models.Sprint

	// Check if the sprint record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", sprintID).First(&sprint, sprint.ID).Error; err != nil {
		return nil, err
	}
	// Check if the document record exists
	var document models.Document
	if res := db.WithContext(tracer.Tracer).Model(&models.Document{}).Where("id = ?", documentID).First(&document); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add document to sprint data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&sprint).Association("Documents").Append(&document); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(document, &sprint_document); err != nil {
		return nil, err
	}
	return sprint_document, nil
}

// Deletedocumentsprint is the resolver for the deletedocumentsprint field.
func (r *mutationResolver) Deletedocumentsprint(ctx context.Context, documentID uint, sprintID uint) (*model.Document, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//sprint_document for return if transaction success
	sprint_document := new(model.Document)

	// updateing document transaction
	var sprint models.Sprint

	// Check if the sprint record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", sprintID).First(&sprint).Error; err != nil {
		return nil, err
	}

	// Check if the document record exists
	var document models.Document
	if res := db.WithContext(tracer.Tracer).Model(&models.Document{}).Where("id = ?", documentID).First(&document); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete  data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&sprint).Association("Documents").Delete(&document); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(document, &sprint_document); err != nil {
		return nil, err
	}
	return sprint_document, nil
}

// Createrequirement is the resolver for the createrequirement field.
func (r *mutationResolver) Createrequirement(ctx context.Context, input model.CreateRequirementInput) (*model.Requirement, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//created requirement initalization
	create_requirement := new(model.Requirement)

	//  initiate -> requirement
	requirement := new(models.Requirement)
	requirement.Name = input.Name
	requirement.Description = input.Description
	requirement.Purpose = input.Purpose
	requirement.BussinessValue = input.BussinessValue
	requirement.Status = string(input.Status)
	requirement.SprintID = input.SprintID
	requirement.AssignedTo = input.AssignedTo

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add requirement using transaction if values are valid
	if err := tx.Create(&requirement).Error; err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(requirement, &create_requirement); err != nil {
		return nil, err
	}
	return create_requirement, nil
}

// Updaterequirement is the resolver for the updaterequirement field.
func (r *mutationResolver) Updaterequirement(ctx context.Context, input model.UpdateRequirementInput) (*model.Requirement, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// updated up for return if transaction success
	update_requirement := new(model.Requirement)

	// startng update transaction
	var requirement models.Requirement
	// Check if the record exists
	if err := db.WithContext(tracer.Tracer).First(&requirement, input.ID).Error; err != nil {
		return nil, err
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add requirement using transaction if values are valid
	if err := tx.Model(&requirement).UpdateColumns(*&input).Error; err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(requirement, &update_requirement); err != nil {
		return nil, err
	}
	return update_requirement, nil
}

// Deleterequirement is the resolver for the deleterequirement field.
func (r *mutationResolver) Deleterequirement(ctx context.Context, id uint) (bool, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// startng update transaction
	var requirement models.Requirement

	// Check if the record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", uint(id)).First(&requirement).Error; err != nil {
		return false, err
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete requirement using transaction if values are valid
	if err := db.Delete(&requirement).Error; err != nil {
		tx.Rollback()
		return false, err
	}
	// close transaction
	tx.Commit()

	return true, nil
}

// Createtestrequirement is the resolver for the createtestrequirement field.
func (r *mutationResolver) Createtestrequirement(ctx context.Context, testID uint, requirementID uint) (*model.Test, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//requirement_test for return if transaction success
	requirement_test := new(model.Test)

	// updateing test transaction
	var requirement models.Requirement

	// Check if the requirement record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", requirementID).First(&requirement, requirement.ID).Error; err != nil {
		return nil, err
	}
	// Check if the test record exists
	var test models.Test
	if res := db.WithContext(tracer.Tracer).Model(&models.Test{}).Where("id = ?", testID).First(&test); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add test to requirement data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&requirement).Association("Tests").Append(&test); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(test, &requirement_test); err != nil {
		return nil, err
	}
	return requirement_test, nil
}

// Deletetestrequirement is the resolver for the deletetestrequirement field.
func (r *mutationResolver) Deletetestrequirement(ctx context.Context, testID uint, requirementID uint) (*model.Test, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//requirement_test for return if transaction success
	requirement_test := new(model.Test)

	// updateing test transaction
	var requirement models.Requirement

	// Check if the requirement record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", requirementID).First(&requirement).Error; err != nil {
		return nil, err
	}

	// Check if the test record exists
	var test models.Test
	if res := db.WithContext(tracer.Tracer).Model(&models.Test{}).Where("id = ?", testID).First(&test); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete  data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&requirement).Association("Tests").Delete(&test); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(test, &requirement_test); err != nil {
		return nil, err
	}
	return requirement_test, nil
}

// Createdocumentrequirement is the resolver for the createdocumentrequirement field.
func (r *mutationResolver) Createdocumentrequirement(ctx context.Context, documentID uint, requirementID uint) (*model.Document, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//requirement_document for return if transaction success
	requirement_document := new(model.Document)

	// updateing document transaction
	var requirement models.Requirement

	// Check if the requirement record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", requirementID).First(&requirement, requirement.ID).Error; err != nil {
		return nil, err
	}
	// Check if the document record exists
	var document models.Document
	if res := db.WithContext(tracer.Tracer).Model(&models.Document{}).Where("id = ?", documentID).First(&document); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add document to requirement data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&requirement).Association("Documents").Append(&document); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(document, &requirement_document); err != nil {
		return nil, err
	}
	return requirement_document, nil
}

// Deletedocumentrequirement is the resolver for the deletedocumentrequirement field.
func (r *mutationResolver) Deletedocumentrequirement(ctx context.Context, documentID uint, requirementID uint) (*model.Document, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//requirement_document for return if transaction success
	requirement_document := new(model.Document)

	// updateing document transaction
	var requirement models.Requirement

	// Check if the requirement record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", requirementID).First(&requirement).Error; err != nil {
		return nil, err
	}

	// Check if the document record exists
	var document models.Document
	if res := db.WithContext(tracer.Tracer).Model(&models.Document{}).Where("id = ?", documentID).First(&document); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete  data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&requirement).Association("Documents").Delete(&document); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(document, &requirement_document); err != nil {
		return nil, err
	}
	return requirement_document, nil
}

// Createtest is the resolver for the createtest field.
func (r *mutationResolver) Createtest(ctx context.Context, input model.CreateTestInput) (*model.Test, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//created test initalization
	create_test := new(model.Test)

	//  initiate -> test
	test := new(models.Test)
	test.Name = input.Name
	test.Description = input.Description
	test.Steps = input.Steps
	test.ExpectedResult = input.ExpectedResult
	test.RequirementID = *input.RequirementID

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add test using transaction if values are valid
	if err := tx.Create(&test).Error; err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(test, &create_test); err != nil {
		return nil, err
	}
	return create_test, nil
}

// Updatetest is the resolver for the updatetest field.
func (r *mutationResolver) Updatetest(ctx context.Context, input model.UpdateTestInput) (*model.Test, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// updated up for return if transaction success
	update_test := new(model.Test)

	// startng update transaction
	var test models.Test
	// Check if the record exists
	if err := db.WithContext(tracer.Tracer).First(&test, input.ID).Error; err != nil {
		return nil, err
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add test using transaction if values are valid
	if err := tx.Model(&test).UpdateColumns(*&input).Error; err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(test, &update_test); err != nil {
		return nil, err
	}
	return update_test, nil
}

// Deletetest is the resolver for the deletetest field.
func (r *mutationResolver) Deletetest(ctx context.Context, id uint) (bool, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// startng update transaction
	var test models.Test

	// Check if the record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", uint(id)).First(&test).Error; err != nil {
		return false, err
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete test using transaction if values are valid
	if err := db.Delete(&test).Error; err != nil {
		tx.Rollback()
		return false, err
	}
	// close transaction
	tx.Commit()

	return true, nil
}

// Createtestset is the resolver for the createtestset field.
func (r *mutationResolver) Createtestset(ctx context.Context, input model.CreateTestsetInput) (*model.Testset, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//created testset initalization
	create_testset := new(model.Testset)

	//  initiate -> testset
	testset := new(models.Testset)
	testset.Name = input.Name
	testset.Description = input.Description

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add testset using transaction if values are valid
	if err := tx.Create(&testset).Error; err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(testset, &create_testset); err != nil {
		return nil, err
	}
	return create_testset, nil
}

// Updatetestset is the resolver for the updatetestset field.
func (r *mutationResolver) Updatetestset(ctx context.Context, input model.UpdateTestsetInput) (*model.Testset, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// updated up for return if transaction success
	update_testset := new(model.Testset)

	// startng update transaction
	var testset models.Testset
	// Check if the record exists
	if err := db.WithContext(tracer.Tracer).First(&testset, input.ID).Error; err != nil {
		return nil, err
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add testset using transaction if values are valid
	if err := tx.Model(&testset).UpdateColumns(*&input).Error; err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(testset, &update_testset); err != nil {
		return nil, err
	}
	return update_testset, nil
}

// Deletetestset is the resolver for the deletetestset field.
func (r *mutationResolver) Deletetestset(ctx context.Context, id uint) (bool, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// startng update transaction
	var testset models.Testset

	// Check if the record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", uint(id)).First(&testset).Error; err != nil {
		return false, err
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete testset using transaction if values are valid
	if err := db.Delete(&testset).Error; err != nil {
		tx.Rollback()
		return false, err
	}
	// close transaction
	tx.Commit()

	return true, nil
}

// Createtesttestset is the resolver for the createtesttestset field.
func (r *mutationResolver) Createtesttestset(ctx context.Context, testID uint, testsetID uint) (*model.Test, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//testset_test for return if transaction success
	testset_test := new(model.Test)

	// updateing test transaction
	var testset models.Testset

	// Check if the testset record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", testsetID).First(&testset, testset.ID).Error; err != nil {
		return nil, err
	}
	// Check if the test record exists
	var test models.Test
	if res := db.WithContext(tracer.Tracer).Model(&models.Test{}).Where("id = ?", testID).First(&test); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add test to testset data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&testset).Association("Tests").Append(&test); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(test, &testset_test); err != nil {
		return nil, err
	}
	return testset_test, nil
}

// Deletetesttestset is the resolver for the deletetesttestset field.
func (r *mutationResolver) Deletetesttestset(ctx context.Context, testID uint, testsetID uint) (*model.Test, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//testset_test for return if transaction success
	testset_test := new(model.Test)

	// updateing test transaction
	var testset models.Testset

	// Check if the testset record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", testsetID).First(&testset).Error; err != nil {
		return nil, err
	}

	// Check if the test record exists
	var test models.Test
	if res := db.WithContext(tracer.Tracer).Model(&models.Test{}).Where("id = ?", testID).First(&test); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete  data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&testset).Association("Tests").Delete(&test); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(test, &testset_test); err != nil {
		return nil, err
	}
	return testset_test, nil
}

// Createtestinstance is the resolver for the createtestinstance field.
func (r *mutationResolver) Createtestinstance(ctx context.Context, input model.CreateTestInstanceInput) (*model.TestInstance, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//created testinstance initalization
	create_testinstance := new(model.TestInstance)

	//  initiate -> testinstance
	testinstance := new(models.TestInstance)
	testinstance.TestsetID = input.TestsetID
	testinstance.TestID = input.TestID

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add testinstance using transaction if values are valid
	if err := tx.Create(&testinstance).Error; err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(testinstance, &create_testinstance); err != nil {
		return nil, err
	}
	return create_testinstance, nil
}

// Createbatchtestinstance is the resolver for the createbatchtestinstance field.
func (r *mutationResolver) Createbatchtestinstance(ctx context.Context, input model.CreateBatchTestInstanceInput) (bool, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// created testinstance initialization
	testinstance := []models.TestInstance{}

	// Iterate over input.TestIds and append new TestInstance objects
	for _, value := range input.TestIds {
		// Capture the new slice after appending
		testinstance = append(testinstance, models.TestInstance{
			TestsetID: input.TestsetID,
			TestID:    value,
			Severity:  string(*input.Severity), // Note: Fixed the typo "Sevierity" to "Severity"
		})
	}

	// start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add testinstance using transaction if values are valid
	if err := tx.Create(&testinstance).Clauses(clause.OnConflict{UpdateAll: true}).Error; err != nil {
		tx.Rollback()
		return false, err
	}
	// close transaction
	tx.Commit()

	return true, nil
}

// Updatetestinstance is the resolver for the updatetestinstance field.
func (r *mutationResolver) Updatetestinstance(ctx context.Context, input model.UpdateTestInstanceInput) (*model.TestInstance, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// updated up for return if transaction success
	update_testinstance := new(model.TestInstance)

	// startng update transaction
	var testinstance models.TestInstance
	// Check if the record exists
	if err := db.WithContext(tracer.Tracer).First(&testinstance, input.ID).Error; err != nil {
		return nil, err
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add testinstance using transaction if values are valid
	if err := tx.Model(&testinstance).UpdateColumns(*&input).Error; err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(testinstance, &update_testinstance); err != nil {
		return nil, err
	}
	return update_testinstance, nil
}

// Deletetestinstance is the resolver for the deletetestinstance field.
func (r *mutationResolver) Deletetestinstance(ctx context.Context, id uint) (bool, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// startng update transaction
	var testinstance models.TestInstance

	// Check if the record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", uint(id)).First(&testinstance).Error; err != nil {
		return false, err
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete testinstance using transaction if values are valid
	if err := db.Unscoped().Delete(&testinstance).Error; err != nil {
		tx.Rollback()
		return false, err
	}
	// close transaction
	tx.Commit()

	return true, nil
}

// Createissuetestinstance is the resolver for the createissuetestinstance field.
func (r *mutationResolver) Createissuetestinstance(ctx context.Context, issueID uint, testInstanceID uint) (*model.Issue, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//testinstance_issue for return if transaction success
	testinstance_issue := new(model.Issue)

	// updateing issue transaction
	var testinstance models.TestInstance

	// Check if the testinstance record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", testInstanceID).First(&testinstance, testinstance.ID).Error; err != nil {
		return nil, err
	}
	// Check if the issue record exists
	var issue models.Issue
	if res := db.WithContext(tracer.Tracer).Model(&models.Issue{}).Where("id = ?", issueID).First(&issue); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add issue to testinstance data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&testinstance).Association("Issues").Append(&issue); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(issue, &testinstance_issue); err != nil {
		return nil, err
	}
	return testinstance_issue, nil
}

// Deleteissuetestinstance is the resolver for the deleteissuetestinstance field.
func (r *mutationResolver) Deleteissuetestinstance(ctx context.Context, issueID uint, testInstanceID uint) (*model.Issue, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//testinstance_issue for return if transaction success
	testinstance_issue := new(model.Issue)

	// updateing issue transaction
	var testinstance models.TestInstance

	// Check if the testinstance record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", testInstanceID).First(&testinstance).Error; err != nil {
		return nil, err
	}

	// Check if the issue record exists
	var issue models.Issue
	if res := db.WithContext(tracer.Tracer).Model(&models.Issue{}).Where("id = ?", issueID).First(&issue); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete  data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&testinstance).Association("Issues").Delete(&issue); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(issue, &testinstance_issue); err != nil {
		return nil, err
	}
	return testinstance_issue, nil
}

// Createtestruntestinstance is the resolver for the createtestruntestinstance field.
func (r *mutationResolver) Createtestruntestinstance(ctx context.Context, testRunID uint, testInstanceID uint) (*model.TestRun, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//testinstance_testrun for return if transaction success
	testinstance_testrun := new(model.TestRun)

	// updateing testrun transaction
	var testinstance models.TestInstance

	// Check if the testinstance record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", testInstanceID).First(&testinstance, testinstance.ID).Error; err != nil {
		return nil, err
	}
	// Check if the testrun record exists
	var testrun models.TestRun
	if res := db.WithContext(tracer.Tracer).Model(&models.TestRun{}).Where("id = ?", testRunID).First(&testrun); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add testrun to testinstance data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&testinstance).Association("TestRuns").Append(&testrun); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(testrun, &testinstance_testrun); err != nil {
		return nil, err
	}
	return testinstance_testrun, nil
}

// Deletetestruntestinstance is the resolver for the deletetestruntestinstance field.
func (r *mutationResolver) Deletetestruntestinstance(ctx context.Context, testRunID uint, testInstanceID uint) (*model.TestRun, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//testinstance_testrun for return if transaction success
	testinstance_testrun := new(model.TestRun)

	// updateing testrun transaction
	var testinstance models.TestInstance

	// Check if the testinstance record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", testInstanceID).First(&testinstance).Error; err != nil {
		return nil, err
	}

	// Check if the testrun record exists
	var testrun models.TestRun
	if res := db.WithContext(tracer.Tracer).Model(&models.TestRun{}).Where("id = ?", testRunID).First(&testrun); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete  data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&testinstance).Association("TestRuns").Delete(&testrun); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(testrun, &testinstance_testrun); err != nil {
		return nil, err
	}
	return testinstance_testrun, nil
}

// Createtestrun is the resolver for the createtestrun field.
func (r *mutationResolver) Createtestrun(ctx context.Context, input model.CreateTestRunInput) (*model.TestRun, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//created testrun initalization
	create_testrun := new(model.TestRun)

	//  initiate -> testrun
	testrun := new(models.TestRun)
	run_status := input.RunStatus.String()
	testrun.RunStatus = run_status
	testrun.Result = input.Result
	testrun.TestInstanceID = input.TestInstanceID

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add testrun using transaction if values are valid
	if err := tx.Create(&testrun).Error; err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(testrun, &create_testrun); err != nil {
		return nil, err
	}

	create_testrun.CreatedAt = &testrun.CreatedAt
	create_testrun.UpdatedAt = &testrun.UpdatedAt
	return create_testrun, nil
}

// Updatetestrun is the resolver for the updatetestrun field.
func (r *mutationResolver) Updatetestrun(ctx context.Context, input model.UpdateTestRunInput) (*model.TestRun, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// updated up for return if transaction success
	update_testrun := new(model.TestRun)

	// startng update transaction
	var testrun models.TestRun
	// Check if the record exists
	if err := db.WithContext(tracer.Tracer).First(&testrun, input.ID).Error; err != nil {
		return nil, err
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add testrun using transaction if values are valid
	if err := tx.Model(&testrun).UpdateColumns(*&input).Error; err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(testrun, &update_testrun); err != nil {
		return nil, err
	}
	return update_testrun, nil
}

// Deletetestrun is the resolver for the deletetestrun field.
func (r *mutationResolver) Deletetestrun(ctx context.Context, id uint) (bool, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// startng update transaction
	var testrun models.TestRun

	// Check if the record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", uint(id)).First(&testrun).Error; err != nil {
		return false, err
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete testrun using transaction if values are valid
	if err := db.Unscoped().Delete(&testrun).Error; err != nil {
		tx.Rollback()
		return false, err
	}
	// close transaction
	tx.Commit()

	return true, nil
}

// Createissuetestrun is the resolver for the createissuetestrun field.
func (r *mutationResolver) Createissuetestrun(ctx context.Context, issueID uint, testRunID uint) (*model.Issue, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//testrun_issue for return if transaction success
	testrun_issue := new(model.Issue)

	// updateing issue transaction
	var testrun models.TestRun

	// Check if the testrun record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", testRunID).First(&testrun, testrun.ID).Error; err != nil {
		return nil, err
	}
	// Check if the issue record exists
	var issue models.Issue
	if res := db.WithContext(tracer.Tracer).Model(&models.Issue{}).Where("id = ?", issueID).First(&issue); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add issue to testrun data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&testrun).Association("Issues").Append(&issue); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(issue, &testrun_issue); err != nil {
		return nil, err
	}
	return testrun_issue, nil
}

// Deleteissuetestrun is the resolver for the deleteissuetestrun field.
func (r *mutationResolver) Deleteissuetestrun(ctx context.Context, issueID uint, testRunID uint) (*model.Issue, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//testrun_issue for return if transaction success
	testrun_issue := new(model.Issue)

	// updateing issue transaction
	var testrun models.TestRun

	// Check if the testrun record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", testRunID).First(&testrun).Error; err != nil {
		return nil, err
	}

	// Check if the issue record exists
	var issue models.Issue
	if res := db.WithContext(tracer.Tracer).Model(&models.Issue{}).Where("id = ?", issueID).First(&issue); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete  data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&testrun).Association("Issues").Delete(&issue); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(issue, &testrun_issue); err != nil {
		return nil, err
	}
	return testrun_issue, nil
}

// Createdocumenttestrun is the resolver for the createdocumenttestrun field.
func (r *mutationResolver) Createdocumenttestrun(ctx context.Context, documentID uint, testRunID uint) (*model.Document, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//testrun_document for return if transaction success
	testrun_document := new(model.Document)

	// updateing document transaction
	var testrun models.TestRun

	// Check if the testrun record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", testRunID).First(&testrun, testrun.ID).Error; err != nil {
		return nil, err
	}
	// Check if the document record exists
	var document models.Document
	if res := db.WithContext(tracer.Tracer).Model(&models.Document{}).Where("id = ?", documentID).First(&document); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add document to testrun data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&testrun).Association("Documents").Append(&document); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(document, &testrun_document); err != nil {
		return nil, err
	}
	return testrun_document, nil
}

// Deletedocumenttestrun is the resolver for the deletedocumenttestrun field.
func (r *mutationResolver) Deletedocumenttestrun(ctx context.Context, documentID uint, testRunID uint) (*model.Document, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//testrun_document for return if transaction success
	testrun_document := new(model.Document)

	// updateing document transaction
	var testrun models.TestRun

	// Check if the testrun record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", testRunID).First(&testrun).Error; err != nil {
		return nil, err
	}

	// Check if the document record exists
	var document models.Document
	if res := db.WithContext(tracer.Tracer).Model(&models.Document{}).Where("id = ?", documentID).First(&document); res.Error != nil {
		return nil, res.Error
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete  data using transaction if values are valid
	if err := db.WithContext(tracer.Tracer).Model(&testrun).Association("Documents").Delete(&document); err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(document, &testrun_document); err != nil {
		return nil, err
	}
	return testrun_document, nil
}

// Createissue is the resolver for the createissue field.
func (r *mutationResolver) Createissue(ctx context.Context, input model.CreateIssueInput) (*model.Issue, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//created issue initalization
	create_issue := new(model.Issue)

	//  initiate -> issue
	issue := new(models.Issue)
	issue.IssueName = input.IssueName
	issue.IssueDescription = input.IssueDescription
	issue.IssueStatus = string(input.IssueStatus)

	if input.TestRunID != nil {
		issue.TestRunID = uint(*input.TestRunID)
	}

	if input.TestInstanceID != nil {
		issue.TestInstanceID = uint(*input.TestInstanceID)
	}

	// fmt.Println(issue)
	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add issue using transaction if values are valid
	if err := tx.Create(&issue).Error; err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(issue, &create_issue); err != nil {
		return nil, err
	}
	return create_issue, nil
}

// Updateissue is the resolver for the updateissue field.
func (r *mutationResolver) Updateissue(ctx context.Context, input model.UpdateIssueInput) (*model.Issue, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// updated up for return if transaction success
	update_issue := new(model.Issue)

	// startng update transaction
	var issue models.Issue
	// Check if the record exists
	if err := db.WithContext(tracer.Tracer).First(&issue, input.ID).Error; err != nil {
		return nil, err
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add issue using transaction if values are valid
	if err := tx.Model(&issue).UpdateColumns(*&input).Error; err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(issue, &update_issue); err != nil {
		return nil, err
	}
	return update_issue, nil
}

// Deleteissue is the resolver for the deleteissue field.
func (r *mutationResolver) Deleteissue(ctx context.Context, id uint) (bool, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// startng update transaction
	var issue models.Issue

	// Check if the record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", uint(id)).First(&issue).Error; err != nil {
		return false, err
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete issue using transaction if values are valid
	if err := db.Unscoped().Delete(&issue).Error; err != nil {
		tx.Rollback()
		return false, err
	}
	// close transaction
	tx.Commit()

	return true, nil
}

// Createdocument is the resolver for the createdocument field.
func (r *mutationResolver) Createdocument(ctx context.Context, input model.CreateDocumentInput) (*model.Document, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//created document initalization
	create_document := new(model.Document)

	//  initiate -> document
	document := new(models.Document)
	document.Name = input.Name

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add document using transaction if values are valid
	if err := tx.Create(&document).Error; err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(document, &create_document); err != nil {
		return nil, err
	}
	return create_document, nil
}

// Updatedocument is the resolver for the updatedocument field.
func (r *mutationResolver) Updatedocument(ctx context.Context, input model.UpdateDocumentInput) (*model.Document, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// updated up for return if transaction success
	update_document := new(model.Document)

	// startng update transaction
	var document models.Document
	// Check if the record exists
	if err := db.WithContext(tracer.Tracer).First(&document, document.ID).Error; err != nil {
		return nil, err
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// add document using transaction if values are valid
	if err := tx.Model(&document).UpdateColumns(*&input).Error; err != nil {
		tx.Rollback()
		return nil, err
	}
	// close transaction
	tx.Commit()

	if err := mapstructure.Decode(document, &update_document); err != nil {
		return nil, err
	}
	return update_document, nil
}

// Deletedocument is the resolver for the deletedocument field.
func (r *mutationResolver) Deletedocument(ctx context.Context, id uint) (bool, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	// startng update transaction
	var document models.Document

	// Check if the record exists
	if err := db.WithContext(tracer.Tracer).Where("id = ?", uint(id)).First(&document).Error; err != nil {
		return false, err
	}

	//  start transaction to database
	tx := db.WithContext(tracer.Tracer).Begin()

	// delete document using transaction if values are valid
	if err := db.Delete(&document).Error; err != nil {
		tx.Rollback()
		return false, err
	}
	// close transaction
	tx.Commit()

	return true, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
