package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.60

import (
	"context"
	"errors"
	"fmt"

	"github.com/mitchellh/mapstructure"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"open-btm.com/common"
	"open-btm.com/graph/model"
	"open-btm.com/models"
)

// Sprints is the resolver for getting list of sprints field.
func (r *queryResolver) Sprints(ctx context.Context, page uint, size uint) (*model.GetSprints, error) {
	db := r.DB         // Database session for querying
	tracer := r.Tracer // otel collector context and span

	sprint_get := make([]*model.Sprint, 0)
	result, _, err := common.PaginationPureModel(db, models.Sprint{}, []models.Sprint{}, uint(page), uint(size), tracer.Tracer)
	if err != nil {
		return nil, err
	}
	sprint := result.Items.([]models.Sprint)
	total := result.Total

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(sprint, &sprint_get); err != nil {
		return nil, err
	}
	return &model.GetSprints{Total: total, Sprints: sprint_get}, nil
}

// Sprint is the resolver for single sprint field.
func (r *queryResolver) Sprint(ctx context.Context, id uint) (*model.Sprint, error) {
	db := r.DB         // database connection
	tracer := r.Tracer //otel tracer span and context

	var sprint models.Sprint    // SQL GORM model
	var sprint_get model.Sprint // graphql model

	if res := db.WithContext(tracer.Tracer).Model(&models.Sprint{}).Where("id = ?", uint(id)).First(&sprint); res.Error != nil {
		if errors.Is(res.Error, gorm.ErrRecordNotFound) {
			return nil, res.Error
		}
		return nil, res.Error
	}

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(sprint, &sprint_get); err != nil {
		return nil, err
	}

	return &sprint_get, nil
}

// Sprintrequirements is the resolver for the getting sprintrequirements field.
func (r *queryResolver) Sprintrequirements(ctx context.Context, sprintID uint, page uint, size uint) (*model.GetRequirements, error) {
	db := r.DB
	tracer := r.Tracer
	requirement_get := make([]*model.Requirement, 0)
	result, _, err := common.PaginationPureModelFilterOneToMany(db, models.Requirement{}, []models.Requirement{}, "sprint_id = ?", uint(sprintID), uint(page), uint(size), tracer.Tracer)
	if err != nil {
		return nil, err
	}
	requirement := result.Items.([]models.Requirement)
	total := result.Total

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(requirement, &requirement_get); err != nil {
		return nil, err
	}

	return &model.GetRequirements{Total: total, Requirements: requirement_get}, nil
}

// Sprintdocuments is the resolver for the getting sprintdocuments field.
func (r *queryResolver) Sprintdocuments(ctx context.Context, sprintID uint, page uint, size uint) (*model.GetDocuments, error) {
	db := r.DB
	tracer := r.Tracer
	document_get := make([]*model.Document, 0)
	result, _, err := common.PaginationPureModelFilterOneToMany(db, models.Document{}, []models.Document{}, "sprint_id = ?", uint(sprintID), uint(page), uint(size), tracer.Tracer)
	if err != nil {
		return nil, err
	}
	document := result.Items.([]models.Document)
	total := result.Total

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(document, &document_get); err != nil {
		return nil, err
	}

	return &model.GetDocuments{Total: total, Documents: document_get}, nil
}

// Requirements is the resolver for getting list of requirements field.
func (r *queryResolver) Requirements(ctx context.Context, page uint, size uint) (*model.GetRequirements, error) {
	db := r.DB         // Database session for querying
	tracer := r.Tracer // otel collector context and span

	requirement_get := make([]*model.Requirement, 0)
	result, _, err := common.PaginationPureModel(db, models.Requirement{}, []models.Requirement{}, uint(page), uint(size), tracer.Tracer)
	if err != nil {
		return nil, err
	}
	requirement := result.Items.([]models.Requirement)
	total := result.Total

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(requirement, &requirement_get); err != nil {
		return nil, err
	}
	return &model.GetRequirements{Total: total, Requirements: requirement_get}, nil
}

// Requirement is the resolver for single requirement field.
func (r *queryResolver) Requirement(ctx context.Context, id uint) (*model.Requirement, error) {
	db := r.DB         // database connection
	tracer := r.Tracer //otel tracer span and context

	var requirement models.Requirement    // SQL GORM model
	var requirement_get model.Requirement // graphql model

	if res := db.WithContext(tracer.Tracer).Model(&models.Requirement{}).Where("id = ?", uint(id)).First(&requirement); res.Error != nil {
		if errors.Is(res.Error, gorm.ErrRecordNotFound) {
			return nil, res.Error
		}
		return nil, res.Error
	}

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(requirement, &requirement_get); err != nil {
		return nil, err
	}

	return &requirement_get, nil
}

// Requirementtests is the resolver for the getting requirementtests field.
func (r *queryResolver) Requirementtests(ctx context.Context, requirementID uint, page uint, size uint) (*model.GetTests, error) {
	db := r.DB
	tracer := r.Tracer
	test_get := make([]*model.Test, 0)
	result, _, err := common.PaginationPureModelFilterOneToMany(db, models.Test{}, []models.Test{}, "requirement_id = ?", uint(requirementID), uint(page), uint(size), tracer.Tracer)
	if err != nil {
		return nil, err
	}
	test := result.Items.([]models.Test)
	total := result.Total

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(test, &test_get); err != nil {
		return nil, err
	}

	return &model.GetTests{Total: total, Tests: test_get}, nil
}

// Requirementdocuments is the resolver for the getting requirementdocuments field.
func (r *queryResolver) Requirementdocuments(ctx context.Context, requirementID uint, page uint, size uint) (*model.GetDocuments, error) {
	db := r.DB
	tracer := r.Tracer
	document_get := make([]*model.Document, 0)
	result, _, err := common.PaginationPureModelFilterOneToMany(db, models.Document{}, []models.Document{}, "requirement_id = ?", uint(requirementID), uint(page), uint(size), tracer.Tracer)
	if err != nil {
		return nil, err
	}
	document := result.Items.([]models.Document)
	total := result.Total

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(document, &document_get); err != nil {
		return nil, err
	}

	return &model.GetDocuments{Total: total, Documents: document_get}, nil
}

// Tests is the resolver for getting list of tests field.
func (r *queryResolver) Tests(ctx context.Context, page uint, size uint) (*model.GetTests, error) {
	db := r.DB         // Database session for querying
	tracer := r.Tracer // otel collector context and span

	test_get := make([]*model.Test, 0)
	result, _, err := common.PaginationPureModel(db, models.Test{}, []models.Test{}, uint(page), uint(size), tracer.Tracer)
	if err != nil {
		return nil, err
	}
	test := result.Items.([]models.Test)
	total := result.Total

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(test, &test_get); err != nil {
		return nil, err
	}
	return &model.GetTests{Total: total, Tests: test_get}, nil
}

// Test is the resolver for single test field.
func (r *queryResolver) Test(ctx context.Context, id uint) (*model.Test, error) {
	db := r.DB         // database connection
	tracer := r.Tracer //otel tracer span and context

	var test models.Test    // SQL GORM model
	var test_get model.Test // graphql model

	if res := db.WithContext(tracer.Tracer).Model(&models.Test{}).Where("id = ?", uint(id)).First(&test); res.Error != nil {
		if errors.Is(res.Error, gorm.ErrRecordNotFound) {
			return nil, res.Error
		}
		return nil, res.Error
	}

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(test, &test_get); err != nil {
		return nil, err
	}

	return &test_get, nil
}

// Getdroptests is the resolver for the getdroptests field.
func (r *queryResolver) Getdroptests(ctx context.Context) ([]*model.DropTest, error) {
	db := r.DB         // Database session for querying
	tracer := r.Tracer // otel collector context and span

	test_get := make([]*model.DropTest, 0)
	tests := make([]models.Test, 0)
	if res := db.WithContext(tracer.Tracer).Model(&models.Test{}).Scan(&tests); res.Error != nil {
		if errors.Is(res.Error, gorm.ErrRecordNotFound) {
			return nil, res.Error
		}
		return nil, res.Error
	}

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(tests, &test_get); err != nil {
		return nil, err
	}
	return test_get, nil
}

// Testsets is the resolver for getting list of testsets field.
func (r *queryResolver) Testsets(ctx context.Context, page uint, size uint) (*model.GetTestsets, error) {
	db := r.DB         // Database session for querying
	tracer := r.Tracer // otel collector context and span

	testset_get := make([]*model.Testset, 0)
	result, _, err := common.PaginationPureModel(db, models.Testset{}, []models.Testset{}, uint(page), uint(size), tracer.Tracer)
	if err != nil {
		return nil, err
	}
	testset := result.Items.([]models.Testset)
	total := result.Total

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(testset, &testset_get); err != nil {
		return nil, err
	}
	return &model.GetTestsets{Total: total, Testsets: testset_get}, nil
}

// Testset is the resolver for single testset field.
func (r *queryResolver) Testset(ctx context.Context, id uint) (*model.Testset, error) {
	db := r.DB         // database connection
	tracer := r.Tracer //otel tracer span and context

	var testset models.Testset    // SQL GORM model
	var testset_get model.Testset // graphql model

	if res := db.WithContext(tracer.Tracer).Model(&models.Testset{}).Preload(clause.Associations).Where("id = ?", uint(id)).First(&testset); res.Error != nil {
		if errors.Is(res.Error, gorm.ErrRecordNotFound) {
			return nil, res.Error
		}
		return nil, res.Error
	}

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(testset, &testset_get); err != nil {
		return nil, err
	}

	return &testset_get, nil
}

// Testsettests is the resolver for the getting testsettests field.
func (r *queryResolver) Testsettests(ctx context.Context, testsetID uint, page uint, size uint) (*model.GetTestSetInstances, error) {
	db := r.DB
	tracer := r.Tracer
	var total int64

	tests_get := make([]*model.InstanceTest, 0)
	// Raw query string
	count_string := `SELECT COUNT(*)
                 FROM test_instances
                 INNER JOIN tests ON test_instances.test_id == tests.id
                 WHERE test_instances.testset_id = ?`

	query_string := `SELECT test_instances.id, test_instances.severity, tests.name,tests.description, tests.steps, tests.expected_result
                 FROM test_instances
                 INNER JOIN tests ON test_instances.test_id == tests.id
                 WHERE test_instances.testset_id = ? order by test_instances.id limit ? offset ?`
	// filter_string := "testset_id = ?"

	//  to make sure no more that 50 items will be queried per request
	if size > 100 {
		size = 100
	}

	//getting total number of items
	if err := db.WithContext(tracer.Tracer).Raw(count_string, testsetID).Count(&total); err.Error != nil {
		return nil, err.Error
	}

	//  actual result query
	tests := make([]models.InstanceTest, 0)
	if err := db.WithContext(tracer.Tracer).Raw(query_string, testsetID, size, page-1).Scan(&tests); err.Error != nil {
		// fmt.Println(err.Error.Error())
		return nil, err.Error
	}

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(tests, &tests_get); err != nil {
		return nil, err
	}
	fmt.Println(tests_get)

	return &model.GetTestSetInstances{Total: uint(total), Testsettests: tests_get}, nil
}

// Testinstances is the resolver for the testinstances field.
func (r *queryResolver) Testinstances(ctx context.Context, page uint, size uint) (*model.GetTestInstances, error) {
	db := r.DB         // Database session for querying
	tracer := r.Tracer // otel collector context and span

	testinstance_get := make([]*model.TestInstance, 0)
	result, _, err := common.PaginationPureModel(db, models.TestInstance{}, []models.TestInstance{}, uint(page), uint(size), tracer.Tracer)
	if err != nil {
		return nil, err
	}
	testinstance := result.Items.([]models.TestInstance)
	total := result.Total

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(testinstance, &testinstance_get); err != nil {
		return nil, err
	}
	return &model.GetTestInstances{Total: total, TestInstances: testinstance_get}, nil
}

// Testinstance is the resolver for the testinstance field.
func (r *queryResolver) Testinstance(ctx context.Context, id uint) (*model.TestInstance, error) {
	db := r.DB         // database connection
	tracer := r.Tracer //otel tracer span and context

	var testinstance models.TestInstance    // SQL GORM model
	var testinstance_get model.TestInstance // graphql model

	if res := db.WithContext(tracer.Tracer).Model(&models.TestInstance{}).Where("id = ?", uint(id)).First(&testinstance); res.Error != nil {
		if errors.Is(res.Error, gorm.ErrRecordNotFound) {
			return nil, res.Error
		}
		return nil, res.Error
	}

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(testinstance, &testinstance_get); err != nil {
		return nil, err
	}

	return &testinstance_get, nil
}

// Testinstanceissues is the resolver for the testinstanceissues field.
func (r *queryResolver) Testinstanceissues(ctx context.Context, testInstanceID uint, page uint, size uint) (*model.GetIssues, error) {
	db := r.DB
	tracer := r.Tracer
	var total int64

	issues_get := make([]*model.Issue, 0)
	join_string := "INNER JOIN testinstance_issues ur ON issues.id = ur.issue_id"
	filter_string := "test_instance_id = ?"

	//  to make sure no more that 50 items will be queried per request
	if size > 100 {
		size = 100
	}

	issues := []models.Issue{}
	//getting total number of items
	if err := db.WithContext(tracer.Tracer).Model(&models.Issue{}).Joins(join_string).Where(filter_string, testInstanceID).Count(&total); err != nil {
		return nil, err.Error
	}

	//  actual result query
	if err := db.WithContext(tracer.Tracer).Model(&models.Issue{}).Joins(join_string).Where(filter_string, testInstanceID).Order("id asc").Limit(int(size)).Offset(int(page - 1)).Find(&issues); err != nil {
		return nil, err.Error
	}

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(issues, &issues_get); err != nil {
		return nil, err
	}

	return &model.GetIssues{Total: uint(total), Issues: issues_get}, nil
}

// Testinstancetestruns is the resolver for the testinstancetestruns field.
func (r *queryResolver) Testinstancetestruns(ctx context.Context, testInstanceID uint, page uint, size uint) (*model.GetTestRuns, error) {
	db := r.DB
	tracer := r.Tracer
	testrun_get := make([]*model.TestRun, 0)
	result, _, err := common.PaginationPureModelFilterOneToMany(db, models.TestRun{}, []models.TestRun{}, "test_instance_id = ?", uint(testInstanceID), uint(page), uint(size), tracer.Tracer)
	if err != nil {
		return nil, err
	}
	testrun := result.Items.([]models.TestRun)
	total := result.Total

	fmt.Println(testrun)
	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(testrun, &testrun_get); err != nil {
		return nil, err
	}

	for index := range testrun {
		testrun_get[index].UpdatedAt = &testrun[index].UpdatedAt
		testrun_get[index].CreatedAt = &testrun[index].CreatedAt
	}
	return &model.GetTestRuns{Total: total, TestRuns: testrun_get}, nil
}

// Testtestruns is the resolver for the testtestruns field.
func (r *queryResolver) Testtestruns(ctx context.Context, testID uint, page uint, size uint) (*model.GetTestRuns, error) {
	db := r.DB
	tracer := r.Tracer
	var total int64

	testrun_get := make([]*model.TestRun, 0)
	// Raw query string
	count_string := `SELECT COUNT(*)
					FROM test_runs
                 INNER JOIN test_instances ON test_runs.test_instance_id == test_instances.id
                 WHERE test_instances.test_id = ? order by test_runs.id`

	query_string := `SELECT test_runs.id,test_runs.created_at, test_runs.updated_at, test_runs.run_status,test_runs.result,test_runs.test_instance_id,test_instances.test_id
				FROM test_runs
				INNER JOIN test_instances ON test_runs.test_instance_id == test_instances.id
				WHERE test_instances.test_id = ? order by test_runs.id limit ? offset ?`

	//  to make sure no more that 100 items will be queried per request
	if size > 100 {
		size = 100
	}

	//getting total number of items
	if err := db.WithContext(tracer.Tracer).Raw(count_string, testID).Count(&total); err.Error != nil {
		return nil, err.Error
	}

	// place holder for data from database
	testrun := make([]models.TestRun, 0)
	if err := db.WithContext(tracer.Tracer).Raw(query_string, testID, size, page-1).Scan(&testrun); err.Error != nil {
		// fmt.Println(err.Error.Error())
		return nil, err.Error
	}

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(testrun, &testrun_get); err != nil {
		return nil, err
	}

	for index := range testrun {
		testrun_get[index].UpdatedAt = &testrun[index].UpdatedAt
		testrun_get[index].CreatedAt = &testrun[index].CreatedAt
	}
	return &model.GetTestRuns{Total: uint(total), TestRuns: testrun_get}, nil
}

// Testruns is the resolver for the testruns field.
func (r *queryResolver) Testruns(ctx context.Context, page uint, size uint) (*model.GetTestRuns, error) {
	db := r.DB         // Database session for querying
	tracer := r.Tracer // otel collector context and span

	testrun_get := make([]*model.TestRun, 0)
	result, _, err := common.PaginationPureModel(db, models.TestRun{}, []models.TestRun{}, uint(page), uint(size), tracer.Tracer)
	if err != nil {
		return nil, err
	}
	testrun := result.Items.([]models.TestRun)
	total := result.Total
	// fmt.Println(testrun)

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(testrun, &testrun_get); err != nil {
		return nil, err
	}

	for index := range testrun {
		testrun_get[index].UpdatedAt = &testrun[index].UpdatedAt
		testrun_get[index].CreatedAt = &testrun[index].CreatedAt
	}

	return &model.GetTestRuns{Total: total, TestRuns: testrun_get}, nil
}

// Testrun is the resolver for the testrun field.
func (r *queryResolver) Testrun(ctx context.Context, id uint) (*model.TestRun, error) {
	db := r.DB         // database connection
	tracer := r.Tracer //otel tracer span and context

	var testrun models.TestRun    // SQL GORM model
	var testrun_get model.TestRun // graphql model

	if res := db.WithContext(tracer.Tracer).Model(&models.TestRun{}).Where("id = ?", uint(id)).First(&testrun); res.Error != nil {
		if errors.Is(res.Error, gorm.ErrRecordNotFound) {
			return nil, res.Error
		}
		return nil, res.Error
	}

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(testrun, &testrun_get); err != nil {
		return nil, err
	}

	return &testrun_get, nil
}

// Testrunissues is the resolver for the testrunissues field.
func (r *queryResolver) Testrunissues(ctx context.Context, testRunID uint, page uint, size uint) (*model.GetIssues, error) {
	db := r.DB
	tracer := r.Tracer
	var total int64

	issues_get := make([]*model.Issue, 0)
	join_string := "INNER JOIN testrun_issues ur ON issues.id = ur.issue_id"
	filter_string := "test_run_id = ?"

	//  to make sure no more that 50 items will be queried per request
	if size > 100 {
		size = 100
	}

	issues := []models.Issue{}
	//getting total number of items
	if err := db.WithContext(tracer.Tracer).Model(&models.Issue{}).Joins(join_string).Where(filter_string, testRunID).Count(&total); err != nil {
		return nil, err.Error
	}

	//  actual result query
	if err := db.WithContext(tracer.Tracer).Model(&models.Issue{}).Joins(join_string).Where(filter_string, testRunID).Order("id asc").Limit(int(size)).Offset(int(page - 1)).Find(&issues); err != nil {
		return nil, err.Error
	}

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(issues, &issues_get); err != nil {
		return nil, err
	}

	return &model.GetIssues{Total: uint(total), Issues: issues_get}, nil
}

// Testrundocuments is the resolver for the testrundocuments field.
func (r *queryResolver) Testrundocuments(ctx context.Context, testRunID uint, page uint, size uint) (*model.GetDocuments, error) {
	db := r.DB
	tracer := r.Tracer
	document_get := make([]*model.Document, 0)
	result, _, err := common.PaginationPureModelFilterOneToMany(db, models.Document{}, []models.Document{}, "test_run_id = ?", uint(testRunID), uint(page), uint(size), tracer.Tracer)
	if err != nil {
		return nil, err
	}
	document := result.Items.([]models.Document)
	total := result.Total

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(document, &document_get); err != nil {
		return nil, err
	}

	return &model.GetDocuments{Total: total, Documents: document_get}, nil
}

// Issues is the resolver for getting list of issues field.
func (r *queryResolver) Issues(ctx context.Context, page uint, size uint) (*model.GetIssues, error) {
	db := r.DB         // Database session for querying
	tracer := r.Tracer // otel collector context and span

	issue_get := make([]*model.Issue, 0)
	result, _, err := common.PaginationPureModel(db, models.Issue{}, []models.Issue{}, uint(page), uint(size), tracer.Tracer)
	if err != nil {
		return nil, err
	}
	issue := result.Items.([]models.Issue)
	total := result.Total

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(issue, &issue_get); err != nil {
		return nil, err
	}
	return &model.GetIssues{Total: total, Issues: issue_get}, nil
}

// Issue is the resolver for single issue field.
func (r *queryResolver) Issue(ctx context.Context, id uint) (*model.Issue, error) {
	db := r.DB         // database connection
	tracer := r.Tracer //otel tracer span and context

	var issue models.Issue    // SQL GORM model
	var issue_get model.Issue // graphql model

	if res := db.WithContext(tracer.Tracer).Model(&models.Issue{}).Where("id = ?", uint(id)).First(&issue); res.Error != nil {
		if errors.Is(res.Error, gorm.ErrRecordNotFound) {
			return nil, res.Error
		}
		return nil, res.Error
	}

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(issue, &issue_get); err != nil {
		return nil, err
	}

	return &issue_get, nil
}

// Documents is the resolver for getting list of documents field.
func (r *queryResolver) Documents(ctx context.Context, page uint, size uint) (*model.GetDocuments, error) {
	db := r.DB         // Database session for querying
	tracer := r.Tracer // otel collector context and span

	document_get := make([]*model.Document, 0)
	result, _, err := common.PaginationPureModel(db, models.Document{}, []models.Document{}, uint(page), uint(size), tracer.Tracer)
	if err != nil {
		return nil, err
	}
	document := result.Items.([]models.Document)
	total := result.Total

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(document, &document_get); err != nil {
		return nil, err
	}
	return &model.GetDocuments{Total: total, Documents: document_get}, nil
}

// Document is the resolver for single document field.
func (r *queryResolver) Document(ctx context.Context, id uint) (*model.Document, error) {
	db := r.DB         // database connection
	tracer := r.Tracer //otel tracer span and context

	var document models.Document    // SQL GORM model
	var document_get model.Document // graphql model

	if res := db.WithContext(tracer.Tracer).Model(&models.Document{}).Where("id = ?", uint(id)).First(&document); res.Error != nil {
		if errors.Is(res.Error, gorm.ErrRecordNotFound) {
			return nil, res.Error
		}
		return nil, res.Error
	}

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(document, &document_get); err != nil {
		return nil, err
	}

	return &document_get, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
