package users

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"errors"
	"fmt"

	"github.com/mitchellh/mapstructure"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"open-btm.com/common"
	"open-btm.com/models"
	"open-btm.com/users/model"
)

// Projects is the resolver for getting list of projects field.
func (r *queryResolver) Projects(ctx context.Context, page uint, size uint) (*model.ProjectResponseGet, error) {
	db := r.DB         // Database session for querying
	tracer := r.Tracer // otel collector context and span

	project_get := make([]*model.Project, 0)
	_, result, err := common.PaginationPureModel(db, models.Project{}, []models.Project{}, uint(page), uint(size), tracer.Tracer)
	if err != nil {
		return nil, err
	}
	project := result.([]models.Project)

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(project, &project_get); err != nil {
		return nil, err
	}
	total := uint(10)
	return &model.ProjectResponseGet{Projects: project_get, Total: total}, nil
}

// Project is the resolver for single project field.
func (r *queryResolver) Project(ctx context.Context, id uint) (*model.Project, error) {
	db := r.DB         // database connection
	tracer := r.Tracer //otel tracer span and context

	var project models.Project    // SQL GORM model
	var project_get model.Project // graphql model

	if res := db.WithContext(tracer.Tracer).Model(&models.Project{}).Preload(clause.Associations).Where("id = ?", uint(id)).First(&project); res.Error != nil {
		if errors.Is(res.Error, gorm.ErrRecordNotFound) {
			return nil, res.Error
		}
		return nil, res.Error
	}

	// filtering response data according to filtered defined struct
	// return error if anything happens
	if err := mapstructure.Decode(project, &project_get); err != nil {
		return nil, err
	}

	return &project_get, nil
}

// Userprojects is the resolver for the userprojects field.
func (r *queryResolver) Userprojects(ctx context.Context, userID uint) ([]*model.Project, error) {
	db := r.DB         // databse connection
	tracer := r.Tracer // otel jaeger tracer

	//  check if user exists
	user, err := models.GetUser(tracer.Tracer, userID)
	if err != nil && user.ID == 0 {
		return nil, fmt.Errorf("User Does not exist or IAM is Down")
	}

	var projects []model.Project
	query_string := `SELECT DISTINCT projects.id, projects.name,projects.description, projects.uuid
			FROM projects
			INNER JOIN project_users pu ON projects.id = pu.project_id
			WHERE pu.user_uuid = ?;`
	if res := db.WithContext(tracer.Tracer).Raw(query_string, user.UUID).Scan(&projects); res.Error != nil {
		return nil, err
	}

	ptrSlice := make([]*model.Project, len(projects))
	for i, project := range projects {
		ptr := project // Create a new local variable to hold the role
		ptrSlice[i] = &ptr
	}

	return ptrSlice, nil
}

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]*model.Role, error) {
	tracer := r.Tracer //otel tracer span and context

	//  creating user via Api call to blue Admin
	roles, err := models.GetAppRoles(tracer.Tracer)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}

	ptrSlice := make([]*model.Role, len(roles))
	for i, role := range roles {
		ptr := role // Create a new local variable to hold the role
		ptrSlice[i] = &ptr
	}
	return ptrSlice, nil
}

// Get Drop Down Users is the resolver for the roles field.
func (r *queryResolver) Dropusers(ctx context.Context) ([]*model.UserGet, error) {
	tracer := r.Tracer //otel tracer span and context

	//  creating user via Api call to blue Admin
	users, err := models.GetDropUsers(tracer.Tracer)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}

	ptrSlice := make([]*model.UserGet, len(users))
	for i, user := range users {
		ptr := user // Create a new local variable to hold the role
		ptrSlice[i] = &ptr
	}
	return ptrSlice, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, page uint, size uint) (*model.UserResponseGet, error) {
	tracer := r.Tracer //otel tracer span and context

	//  creating user via Api call to blue Admin
	users, err := models.GetUsers(tracer.Tracer, page, size)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}

	ptrSlice := make([]*model.UserGet, len(users))
	for i, user := range users {
		ptr := user // Create a new local variable to hold the role
		ptrSlice[i] = &ptr
	}
	total := uint(10)

	return &model.UserResponseGet{Users: ptrSlice, Total: total}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id uint) (*model.UserGet, error) {
	tracer := r.Tracer //otel tracer span and context

	//  creating user via Api call to blue Admin
	user, err := models.GetUser(tracer.Tracer, id)
	if err != nil {
		fmt.Println(err)
		return nil, err
	}

	return user, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
